/* ================================================================
   ACADEMY VIDEO LIBRARY — the individual training videos uploaded to
   YouTube. Bundled here so they're immediately searchable in the
   Content Hub (as one video per item, not a "10 videos" bundle).
   When these land in the Asana Videos project as subtasks, the live
   read will supersede this seed.
   ================================================================ */
const ACADEMY_VIDEO_SEED = [
  ["Pre-Rolling Sushi","https://youtu.be/DZetRB7_hi0"],
  ["Birthday big day readiness Franchisee session","https://youtu.be/kNVzRbkthfw"],
  ["Frying Calamari","https://youtu.be/S9R9fxg1dSc"],
  ["How to Fillet a Salmon","https://youtu.be/swG_SQJ_YgA"],
  ["How to cook sushi rice","https://youtu.be/pvoCLlrg4S0"],
  ["How to use the blow torch","https://youtu.be/HZLRW8HKCEo"],
  ["How to roll California Rolls","https://youtu.be/OiBfknc5FeU"],
  ["How to roll Maki","https://youtu.be/bauTPav4T_M"],
  ["How to portion Sushi garnish","https://youtu.be/yIoS1St1W04"],
  ["How to sharpen your sushi knife","https://youtu.be/1qTDIkxTj6E"],
  ["Birthday Readiness Managers","https://youtu.be/UcamZ0XPMgI"],
  ["Franchisee session Birthday Readiness","https://youtu.be/rSn1qlzoni4"],
  ["How to fry fish","https://youtu.be/DmpQiLgND24"],
  ["How to fry calamari","https://youtu.be/sL2n0S6bAgg"],
  ["Tempura Crunch Topping","https://youtu.be/555rQo5_G4Y"],
  ["Sushi Masterclass June 2026","https://youtu.be/ko5TaofqV2U"],
  ["Salmon Favourites","https://youtu.be/bhDaiEJ0ju0"],
  ["Manager Winter Launch","https://youtu.be/3sv4mv3zJcs"],
  ["Business update franchisee","https://youtu.be/X9xiz8xYH30"],
  ["Tempura Prawn and Salmon roll","https://youtu.be/93QPwnjc6Q0"],
  ["The crunch platter","https://youtu.be/MuG6pf1a1-M"],
  ["Loaded Prawn Futomaki","https://youtu.be/lKhEW-9HBFE"],
  ["Golden Crunch Prawn California Roll","https://youtu.be/3LciEX4sM4w"],
  ["Fire Cracker Calamari Roll","https://youtu.be/qU9zFD8T_uc"],
  ["Seared Tuna","https://youtu.be/wromcC8Fopc"],
  ["Saucy Panko Salmon Futomaki","https://youtu.be/EeLr_N22duE"],
  ["New Wave Platter","https://youtu.be/VAc-Sq0QMMc"],
  ["Grilled Halloumi","https://youtu.be/ITdtbVvPEPE"],
  ["Sushi for one","https://youtu.be/PbpP_ofNziw"],
  ["Fired Halloumi","https://youtu.be/hZJali41Rbs"],
  ["Sushi for Two","https://youtu.be/AuZXM_UkKrE"],
  ["Sushi Two Way","https://youtu.be/PJ1D3JGkM8I"],
  ["Cajun Halloumi","https://youtu.be/-9VDc--Pazk"],
  ["Lemon Mint Cooler","https://youtu.be/I3RjmAis3Oc"],
  ["Fried Fish Burger","https://youtu.be/GcWoILyCfuE"],
  ["Frozen Mojito","https://youtu.be/_2lGsVl4bqY"],
  ["Epic Bomb Platter","https://youtu.be/wlcJcQwLBZ0"],
  ["Firecracker Calamari Roll","https://youtu.be/FjbWVDwh1dE"],
  ["New Fusion Platter","https://youtu.be/unoJmejTSWw"],
  ["Business Update OB Rewards 13 May","https://youtu.be/DBd3LVz1ge0"],
  ["Learn about our brand","https://youtu.be/jY_5QPovsXU"],
  ["Trade Bridge Additional Training","https://youtu.be/SC9dBbxavzg"],
  ["How to make rock shrimp tempura","https://youtu.be/k1rr13Vj-6E"],
  ["How to plate sushi 14","https://youtu.be/I-HwJJeTeEI"],
  ["May-June Volume Drivers","https://youtu.be/jNyn-cBFJVs"],
  ["Harbour Box","https://youtu.be/aJcIh843Ptw"],
  ["How to make Avo Maki","https://youtu.be/PEXt-41p9hg"],
  ["How to roll saucy rainbow rolls","https://youtu.be/EIeygnr45EM"],
  ["Prawn and Corn Bites","https://youtu.be/rlevkyeqO8A"],
  ["Reel Love Platter","https://youtu.be/1DOuo6xEviI"],
  ["Salmon Roses (4)","https://youtu.be/t41zBRRvaec"],
  ["Saucy Legends","https://youtu.be/ai7vejw3_5A"],
  ["Burn the Bill","https://youtu.be/SDVC3U9X8Qc"],
  ["OB Rewards | Trade Bridge","https://youtu.be/W3nE43S-qgE"],
  ["OB Rewards | How the financials work","https://youtu.be/27mw3npSqyA"],
  ["Top Tips for Busy Shifts","https://youtu.be/MTcEWmPaWB4"],
  ["How to sauce our sushi","https://youtu.be/rzVDbar7q0I"],
  ["Colour coding and food safety","https://youtu.be/J1BJ9_zPZ6I"],
  ["Scheduling for the Season Ahead","https://youtu.be/c2nC9wJiHic"],
  ["The Perfect Catch Platter","https://youtu.be/HeQ_WZou-fc"],
  ["Sushi Platter 11 + Soda","https://youtu.be/eLXezirdw_I"],
  ["Sushi 16","https://youtu.be/9StMGc4yKKI"],
  ["Panko Fish Burger","https://youtu.be/QQ9jtlnk5Mo"],
  ["The Oceans Platter","https://youtu.be/oLVGFTfew0U"],
  ["How to Plate Sushi Platters","https://youtu.be/7LrOAc4CqfE"],
  ["A day in the life of a sushi chef","https://youtu.be/0GPH7jvXC9o"],
  ["Cooking and Plating the perfect platter for two","https://youtu.be/uq_mE5qSKuE"],
  ["Preparing Queen Prawns","https://youtu.be/REvU2UfwSsI"],
  ["Removing the beards from our mussels","https://youtu.be/qAUOMGqJhZ4"],
  ["Basmati Rice","https://youtu.be/QG6_UbKyT9I"],
  ["Chunky House Salad","https://youtu.be/JOiBtZz-9Y0"],
  ["Panko Prawns","https://youtu.be/1oIIv337NTY"],
  ["Salmon Ceviche","https://youtu.be/_nsa4QUokhg"],
  ["Green Garnish","https://youtu.be/ldjdjz4vKCg"],
  ["Cherry Tomatoes","https://youtu.be/jXBf2nrEdRY"],
  ["Cutting a lemon","https://youtu.be/6sgEOcyLVmg"],
  ["How to pickle cucumber","https://youtu.be/Xm_08TZCwoE"],
  ["How to Make Veggie Ribbons","https://youtu.be/uICZghB_078"],
  ["Avo Crema","https://youtu.be/8Q5obas_TnU"],
  ["Malva Pudding","https://youtu.be/LDzWRJ_ayho"],
  ["Spicy Mayo","https://youtu.be/iOMTidPqZP0"],
  ["OB Batter Mix","https://youtu.be/AV8oMcTf-Lk"],
  ["Village Salad","https://youtu.be/VNw6ehBeFiM"],
  ["How to cut a 10/12 hake","https://youtu.be/NZbkohcp_14"],
  ["How to cut a 6/8 hake","https://youtu.be/e5dMcds6NVI"],
  ["How to cut a 2/4 hake","https://youtu.be/q9hy2fX-nI0"],
  ["How to bake bread","https://youtu.be/BVbIxm1TSTU"],
  ["Salmon Tartare roll prep","https://youtu.be/GsSs3rY9cLI"],
  ["How to Clean Calamari","https://youtu.be/rL1q2OtGDgM"],
  ["How to clean prawns","https://youtu.be/xu-BEWmemkI"],
  ["Spicing Prawns","https://youtu.be/9M157PNMl68"],
  ["How to cook prawns","https://youtu.be/q5IDDxDNq-Y"],
  ["Portioning Hake","https://youtu.be/wK_M66MCrnA"],
  ["How to slice green peppers","https://youtu.be/9QhRESYqGw8"],
  ["How to cut cucumbers","https://youtu.be/-NputDJeD34"],
  ["How to cut onions","https://youtu.be/ICaJ2WKCuSY"],
  ["Opening Closing and Tendering of tables (Pilot)","https://youtu.be/S1SkKb7QS8I"],
  ["Adding Users (Pilot)","https://youtu.be/PVS8IV5FXto"],
  ["Setting Up User Functions (Pilot)","https://youtu.be/71TZQJ745JA"],
  ["Linking Expenses (Pilot)","https://youtu.be/OcsZHkMelb8"],
  ["Sea Bream","https://youtu.be/eyqUhVYudyU"],
  ["How to skin kingklip","https://youtu.be/ZCvh1hyKvXI"],
  ["Founders and mama liza","https://youtu.be/yecWVvVJtyw"],
  ["Redeeming and checking an online voucher on pilot","https://youtu.be/_7zUYOKKKhE"],
  ["Redeeming and checking an online voucher (Pilot)","https://youtu.be/IIBO6bW4Rzg"],
  ["How to clean the flat top","https://youtu.be/5UgKNl5JQZ0"],
  ["How to clean calamari","https://youtu.be/9H4786gDKgE"],
  ["How to clean Prawns","https://youtu.be/pAhAqZntd-w"],
  ["How to clean the dishwasher","https://youtu.be/J7GVctAtWhM"],
  ["Storage Basics","https://youtu.be/0oCOt3HEjhs"],
  ["Gas Efficiencies","https://youtu.be/q9sPwFnjflw"],
  ["Mussels from receiving to cooking","https://youtu.be/yVFqVihSxME"],
  ["Garbage disposal","https://youtu.be/w3c7sYgyXo8"],
  ["Scullery Walk Through","https://youtu.be/dKbWuDaPQxM"],
  ["Managing the Dump Hatch","https://youtu.be/wAl8nR3_HHc"],
  ["Team Dashboard WhatsApp Tutorial","https://youtube.com/shorts/zXHzXuT_Dmg"],
  ["Loyalty app Launch V2","https://youtu.be/y8jhBVAXm84"],
  ["OB Academy tutorial V3","https://youtube.com/shorts/K99iwMHvSmc"],
  ["Cyprus Hype Final","https://youtube.com/shorts/JLstC_88u4g"],
  ["Queen Prawn Disclaimer","https://youtu.be/hD7i4C-L4ag"],
  ["Full Shell Mussel Disclaimer","https://youtu.be/qOMQG2e7YlA"],
  ["Half Shell Mussels","https://youtu.be/UP_vTd58iTQ"],
  ["How to open and pour a beer","https://youtu.be/XvhnAP1W0YU"],
  ["How to plate seafood trio","https://youtu.be/hegoiq6MXps"],
  ["How to plate the summer wave platter","https://youtu.be/Fjjq0YHZJas"],
  ["How to plate sushi 13 platter","https://youtu.be/8MWGCqmK3GE"],
  ["How to cook sushi rice (alt)","https://youtu.be/pvoCLlrg4S0"]
];

// Light keyword bucketing so the library (and the wheel) can group them.
function videoCategory(title){
  const t = String(title||"").toLowerCase();
  if(/pilot|adding users|user functions|expenses|voucher|tendering|dashboard|loyalty app|academy tutorial|whatsapp tutorial/.test(t)) return "Systems & Pilot";
  if(/franchisee|business update|ob rewards|trade bridge|financials|founders|brand|scheduling|colour coding|storage|gas|garbage|scullery|dump hatch|dishwasher|flat top|disposal|top tips|receiving/.test(t)) return "Business & Ops";
  if(/masterclass|launch|birthday readiness|cyprus hype|volume drivers|disclaimer|hype/.test(t)) return "Launch & Seasonal";
  if(/sushi|maki|futomaki|cali|california roll|rainbow|roses|nigiri|tempura|salmon roll|panko salmon|garnish|blow torch|sauce our sushi|plate sushi|salmon tartare/.test(t)) return "Sushi";
  if(/^how to|prep|cut |clean|fillet|skin|portion|sharpen|pickle|ribbons|spicing|cook prawns|slice|bake bread|basmati|batter|crema|spicy mayo|preparing|removing|beards/.test(t)) return "Prep skills";
  return "Dishes & drinks";
}
function academyVideoRecords(){
  return ACADEMY_VIDEO_SEED.map(([title,url],i)=>({
    id:"vid:"+i, kind:"seed", name:title, notes:"", asana:null, source:"videos",
    collection:"Video library", section:null, moduleCount:0, owner:null, fields:{},
    updated:null, type:"Videos", role:"", programme:videoCategory(title),
    published:url, edit:"", archived:false, needs:false, youtube:url
  }));
}
